<?php
/**
 * Created by Malik Abiola.
 * Date: 02/02/2016
 * Time: 01:45
 * IDE: PhpStorm
 */

namespace Paystack\Tests;

use Paystack\Transaction;

class TransactionTest extends BaseTestCase
{
    protected $payStackTransaction;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->payStackTransaction = new Transaction();
    }

    public function testInitiateTransaction()
    {
        $transInit = $this->payStackTransaction->initiate($this->transactionRequestArray['amount'], $this->transactionRequestArray['email']);
        $this->assertArrayHasKey('access_code', $transInit);
        $this->assertArrayHasKey('authorization_url', $transInit);
        $this->assertTrue($transInit['status']);
    }
}
